import { useState, type FormEvent } from 'react';
import type { ProductInput, TuckShopProduct } from '../types';

interface AdminProps { products: TuckShopProduct[]; onAddProduct: (input: ProductInput) => Promise<void>; onRestock: (product: TuckShopProduct, amount: number) => Promise<void>; onExit: () => void; }
const initialForm: ProductInput = { name: '', aliasesText: '', category: '음료', price: 0, stockDate: new Date().toISOString().slice(0, 10), stockQuantity: 1, calories: undefined };
export default function AdminDashboard({ products, onAddProduct, onRestock, onExit }: AdminProps) {
  const [form, setForm] = useState<ProductInput>(initialForm); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const update = <K extends keyof ProductInput>(key: K, value: ProductInput[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.name.trim() || form.price < 0 || form.stockQuantity < 1) return setMessage('상품명, 가격, 입고 개수를 확인해 주세요.'); setBusy(true); try { await onAddProduct(form); setForm({ ...initialForm, stockDate: new Date().toISOString().slice(0, 10) }); setMessage('상품을 등록했습니다. 사용자 화면에 바로 반영됩니다.'); } catch { setMessage('상품 등록에 실패했습니다. Firestore 권한을 확인해 주세요.'); } finally { setBusy(false); } };
  const restock = async (product: TuckShopProduct) => { const amount = Number(window.prompt(`${product.name}에 추가할 입고 개수`, '1')); if (!Number.isInteger(amount) || amount < 1) return; try { await onRestock(product, amount); } catch { setMessage('재입고 처리에 실패했습니다.'); } };
  return <main className="admin-shell"><header className="admin-header"><div><p className="eyebrow">ADMIN DASHBOARD</p><h1>매점 상품 관리</h1></div><button className="secondary-button" onClick={onExit}>사용자 화면으로</button></header><div className="admin-grid"><form className="admin-form" onSubmit={submit}><h2>새 상품 입고</h2><label>상품명<input value={form.name} placeholder="예: 포카리스웨트 355ML" onChange={(event) => update('name', event.target.value)} /></label><label>검색 별칭 <small>쉼표로 구분 (예: 포카리, POCARI)</small><input value={form.aliasesText} placeholder="포카리, POCARI" onChange={(event) => update('aliasesText', event.target.value)} /></label><div className="form-columns"><label>상품 종류<select value={form.category} onChange={(event) => update('category', event.target.value)}><option>음료</option><option>과자</option><option>젤리</option><option>캔디</option><option>라면</option><option>기타</option></select></label><label>가격(원)<input type="number" min="0" value={form.price || ''} onChange={(event) => update('price', Number(event.target.value))} /></label></div><div className="form-columns"><label>입고 날짜<input type="date" value={form.stockDate} onChange={(event) => update('stockDate', event.target.value)} /></label><label>입고 개수<input type="number" min="1" value={form.stockQuantity || ''} onChange={(event) => update('stockQuantity', Number(event.target.value))} /></label></div><label>칼로리 (선택)<input type="number" min="0" value={form.calories ?? ''} onChange={(event) => update('calories', event.target.value ? Number(event.target.value) : undefined)} /></label><button className="primary-button" disabled={busy}>{busy ? '등록 중…' : '상품 등록하기'}</button>{message && <p className="admin-message">{message}</p>}</form><section className="admin-products"><h2>현재 상품 현황 <small>{products.length}개</small></h2>{products.length ? <ul>{products.map((product) => <li key={product.id}><div><strong>{product.name}</strong><p>{product.category} · {product.price.toLocaleString()}원 · 입고 {product.stockDate.toLocaleDateString('ko-KR')}</p><small>별칭: {product.aliases.length ? product.aliases.join(', ') : '없음'}</small></div><div className="stock"><b>재고 {product.currentStock}</b><button onClick={() => void restock(product)}>+ 입고</button></div></li>)}</ul> : <p className="empty-message">등록된 상품이 없습니다.</p>}</section></div></main>;
}
