import { useState, type FormEvent } from 'react';
import type { PurchaseLog, Recommendation, Student } from '../types';
interface Props { student: Student | null; recentLog?: PurchaseLog; frequentProduct?: { name: string; count: number }; recommendations: Recommendation[]; onLogin: (id: string, password: string) => Promise<void>; onLogout: () => void; onChangePassword: (password: string) => Promise<void>; onAddRecommendation: (name: string) => Promise<void>; onToggleRecommendation: (item: Recommendation) => Promise<void>; onOpenPurchase: () => void; onEnterAdmin: () => void; }
export default function Home(props: Props) {
  const [studentId, setStudentId] = useState(''); const [password, setPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [wish, setWish] = useState(''); const [adminOpen, setAdminOpen] = useState(false); const [adminPassword, setAdminPassword] = useState(''); const [error, setError] = useState(''); const [passwordSuccess, setPasswordSuccess] = useState(false);
  const run = async (work: () => Promise<void>) => { setError(''); try { await work(); } catch (reason) { setError(reason instanceof Error ? reason.message : '요청 처리에 실패했습니다.'); } };
  const changePassword = async () => { setError(''); try { await props.onChangePassword(newPassword); setPasswordSuccess(true); window.setTimeout(() => setPasswordSuccess(false), 1500); } catch (reason) { setError(reason instanceof Error ? reason.message : '비밀번호 변경에 실패했습니다.'); } };
  const admin = () => { if (adminPassword === '1234') props.onEnterAdmin(); else setError('관리자 비밀번호가 올바르지 않습니다.'); };
  if (!props.student) return <div className="page-stack"><section className="hero-card"><p className="eyebrow">MAEJUM EASY</p><h1>울산여고 매점이지</h1><p>학번으로 로그인해 구매 기록과 매점 수요를 확인하세요.<br />초기 비밀번호는 1234입니다.</p></section><form className="glass-card login-form" onSubmit={(event) => { event.preventDefault(); void run(() => props.onLogin(studentId, password)); }}><label>학번 5자리<input inputMode="numeric" maxLength={5} value={studentId} onChange={(event) => setStudentId(event.target.value.replace(/\D/g, ''))} placeholder="10420" /></label><label>비밀번호<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="초기 비밀번호 1234" /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button">로그인</button></form><button className="admin-link" onClick={() => setAdminOpen(true)}>관리자 전용</button>{adminOpen && <AdminModal password={adminPassword} onChange={setAdminPassword} onClose={() => setAdminOpen(false)} onEnter={admin} />}</div>;
  return <div className="page-stack"><section className="hero-card"><p className="eyebrow">WELCOME</p><h1>{props.student.studentId} 학생, 안녕하세요</h1><p>상품을 찾아 구매 기록을 남기고, 원하는 상품을 추천해 보세요.</p><button className="primary-button" onClick={props.onOpenPurchase}>상품 구매 기록하기 <span>→</span></button></section>{props.student.mustChangePassword && <form className="glass-card password-card" onSubmit={(event) => { event.preventDefault(); void changePassword(); }}><strong>초기 비밀번호를 변경해 주세요</strong><input type="password" minLength={4} required value={newPassword} onChange={(event) => setNewPassword(event.target.value)} placeholder="새 비밀번호 4자리 이상" /><button className="primary-button">비밀번호 변경</button></form>}<section className="glass-card recent-card"><div><p className="eyebrow">최근 구매</p>{props.recentLog ? <><strong>{props.recentLog.productName}</strong><p>{props.recentLog.category} · {props.recentLog.timestamp.toLocaleString('ko-KR')}</p></> : <p>아직 구매 기록이 없어요.</p>}</div><span className="bubble-icon">🧃</span></section><section className="glass-card frequent-card"><p className="eyebrow">나의 최다 구매</p>{props.frequentProduct ? <><strong>{props.frequentProduct.name}</strong><p>총 {props.frequentProduct.count}회 구매했어요.</p></> : <p>구매 기록이 쌓이면 자주 구매한 상품을 알려드려요.</p>}</section><section className="glass-card demand-card"><h2>입고 희망 상품</h2><form onSubmit={(event: FormEvent) => { event.preventDefault(); if (wish.trim()) void run(async () => { await props.onAddRecommendation(wish.trim()); setWish(''); }); }}><input value={wish} onChange={(event) => setWish(event.target.value)} placeholder="매점에 들어왔으면 하는 상품" /><button className="primary-button">추천</button></form><div className="recommendations">{props.recommendations.map((item) => <button key={item.id} className={item.supporters.includes(props.student!.studentId) ? 'heart-item liked' : 'heart-item'} onClick={() => void run(() => props.onToggleRecommendation(item))}>♥ {item.name}<small>{item.supporters.length}</small></button>)}</div></section>{error && <p className="form-error">{error}</p>}<button className="text-button" onClick={props.onLogout}>로그아웃</button><button className="admin-link" onClick={() => setAdminOpen(true)}>관리자 전용</button>{adminOpen && <AdminModal password={adminPassword} onChange={setAdminPassword} onClose={() => setAdminOpen(false)} onEnter={admin} />}{passwordSuccess && <div className="modal-backdrop"><div className="success-modal"><span>✓</span><h2>비밀번호가 안전하게 변경되었습니다!</h2><p>잠시 후 메인 화면으로 이동합니다.</p></div></div>}</div>;
}
function AdminModal({ password, onChange, onClose, onEnter }: { password: string; onChange: (value: string) => void; onClose: () => void; onEnter: () => void }) { return <div className="modal-backdrop"><div className="success-modal admin-modal"><h2>관리자 모드</h2><input autoFocus type="password" value={password} onChange={(event) => onChange(event.target.value)} placeholder="비밀번호" /><div className="modal-actions"><button className="secondary-button" onClick={onClose}>취소</button><button className="primary-button" onClick={onEnter}>확인</button></div></div></div>; }
